version: "3.9"
services:
  frontend:
    container_name: podcaster-app
    image: podcaster-app/v3.0.0
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "8080:80"
    environment:
      - VITE_ITUNES_BASE_URL=https://itunes.apple.com
      - VITE_ITUNES_PODCASTS_URL=/us/rss/toppodcasts/limit=100/genre=1310/json
      - VITE_ITUNES_PODCAST_LOOKUP_URL=/lookup?id=
      - VITE_ITUNES_PARAMS_URL=&media=podcast&entity=podcastEpisode&limit=20
networks:
  frontend:
    name: podcaster-app