version: "3.9"
services:
  frontend:
    container_name: podcaster-app
    image: podcaster-app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "5173:5173"
    volumes:
      - "/app/node_modules"
      - "./:/app"
networks:
  frontend:
    name: podcaster-app